name: 构建多平台版本

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: 设置 Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pandas openpyxl PyQt6

    - name: 打包程序
      run: |
        cd assets
        python 打包程序.py

    - name: 上传构建产物
      uses: actions/upload-artifact@v3
      with:
        name: 抽签小程序-${{ matrix.os }}
        path: assets/抽签小程序_便携版/
